#!/usr/bin/guile
!#

(use-modules (ice-9 match) (ice-9 threads))

(define test-get-info
  (match (command-line)
    ((or (cmd) (cmd "good-battery"))
     (const
       '((vendor . "ACME")
         (model . "B1")
         (energy-full-design . 99)
         (technology . 2)
         (energy-full . 90)
         (capacity . 90))))
    ((cmd "no-battery") (const #f))
    ((cmd "error") (lambda () (error "test error")))
    (else (error "Please specify test from: good-battery no-battery error"))))

(add-to-load-path (dirname (current-filename)))
(use-modules (battery info))

(join-thread (show-battery-info test-get-info))
        

